version: "3"

volumes:
  mysqlstorage:

services:
  node:
    build:
      context: .
      dockerfile: node.Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./:/volume
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: "npm run start"
    environment:
      DB_URL: mysql
    links:
      - mysql
    depends_on:
      - mysql
  
  mysql:
    image: 'mysql:5.7'
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    build:
      context: .
      dockerfile: db.Dockerfile
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    volumes:
      - mysqlstorage:/data/db
    ports:
      - "3306:3306"